---
- name: Ensure docker-compose.yml for containers is present
  become: true
  become_user: "{{ ansible_user }}"
  synchronize:
    src: data/containers
    dest: "{{ base_path }}"
  notify: docker restart
