---

# How to create encrypted passwords for the user module 
# https://docs.ansible.com/ansible/latest/reference_appendices/faq.html#how-do-i-generate-encrypted-passwords-for-the-user-module
# The custom password for the pi user is in this example raspberry
pi_custom_password: $6$c04cOXDbcDZ$fobZpDfUp1gOfICS9B5MNmzr9BnNL8gzjPBZnfoYLG/VCYSXFChljrMgczA9WI.TdNXIHtSCVKEJ36suDK1s4/

# base location for all application setup
base_path: /home/pi

# flag to enable/disable backup and sync
ensure_backup: True

# flag to enable/disable automatic updates
ensure_autoupdate: True

# flag to enable/disable daily usage reporting
ensure_reporting: False

# pihole configuration
pihole_tz: Europe/London
pihole_password: pihole

# rclone configuration
# Use this link to create the dropbox token https://rclone.org/dropbox/
rclone_type: dropbox
rclone_token: {"access_token":"XXXX","token_type":"Bearer","refresh_token":"YYYY,"expiry":"ZZZZ"}

# discord configuration
webhook_url: https://discordapp.com/api/webhooks/xxx/yyy

# certificate configuration
cert_detail: /C=IN/ST=West Bengal/L=Kolkata/O=Home, Inc./OU=Vaultwarden/CN=VaultPI Vaultwarden
