---
- name: Server Hardening
  hosts: vault_pi
  become: yes

  vars_files:
    - config.yml

  pre_tasks:
    - name: pre tasks
      ansible.builtin.import_tasks: tasks/pre.yml

  tasks:
    - name: Sample Task
      ansible.builtin.command: "hostname"

- name: Backup Management
  hosts: vault_pi
  become: yes

  vars_files:
    - config.yml

  handlers:
    - name: Include Sync-Restore Handlers
      ansible.builtin.import_tasks: handlers/sync_restore.yml

    - name: Include Backup-Restore Handlers
      ansible.builtin.import_tasks: handlers/backup_restore.yml

    - name: Include Scheduling Handlers
      ansible.builtin.import_tasks: handlers/schedule_backups.yml

  tasks:
    - name: Setup Rclone
      ansible.builtin.import_tasks: tasks/backups/rclone.yml

    - name: Setup BorgBackup
      ansible.builtin.import_tasks: tasks/backups/borg.yml

    - name: Setup Backups and Sync Scripts
      ansible.builtin.import_tasks: tasks/backups/scheduling.yml

- name: E-Ink Display Management
  hosts: vault_pi
  become: yes

  vars_files:
    - config.yml

  handlers:
    - name: Include Waveshare Driver Handlers
      ansible.builtin.import_tasks: handlers/waveshare_driver.yml

  tasks:
    - name: Setup SPI
      ansible.builtin.import_tasks: tasks/display/spi.yml

    - name: Setup Display Refresh Scripts
      ansible.builtin.import_tasks: tasks/display/display.yml

- name: Container Setup
  hosts: vault_pi
  become: yes

  vars_files:
    - config.yml

  post_tasks:
    - name: Filesystem Cleanup
      ansible.builtin.import_tasks: tasks/post.yml

  handlers:
    - name: Include Docker Handlers
      ansible.builtin.import_tasks: handlers/docker_restart.yml

  tasks:
    - name: Setup Docker
      ansible.builtin.import_tasks: tasks/containers/docker.yml

    - name: Setup Containers
      ansible.builtin.import_tasks: tasks/containers/containers.yml
