---
- name: Check if /tmp/openssl.conf file exists
  stat:
    path: /tmp/openssl.conf
  register: tmp_openssl

- name: Remove /tmp/openssl.conf file
  command: /tmp/openssl.conf
  when: tmp_openssl.stat.exists == True

- name: Cleanup /tmp directory
  command: rm -rf /tmp/*


- name: Cleanup ~/.ansible/tmp directory
  command: rm -rf /home/{{ ansible_user }}/.ansible/tmp
