---
- name: Ensure apt cache is up to date.
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Ensure dependencies are installed
  ansible.builtin.apt:
    name: 
      - python3-pip
      - python3-numpy
      - python3-venv
      - libatlas-base-dev
      - libjpeg62
      - libopenjp2-7
      - libtiff5
      - libxcb1
    state: present

- name: Ensure pip dependencies are installed
  pip:
    name: pexpect
