---
- name: Ensure apt cache is up to date.
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Ensure pip is installed
  ansible.builtin.apt:
    name: python3-pip
    state: present

- name: Ensure pip dependencies are installed
  pip:
    name: pexpect
