---
- name: Ensure a backup job runs every saturday at 23:00
  become: true
  become_user: "{{ ansible_user }}"
  ansible.builtin.cron:
    name: "take backup"
    minute: "0"
    hour: "23"
    weekday: "6"
    job: "sudo sh {{ base_path }}/backup_sync/do_backup.sh > /dev/null 2>&1"
  listen: "schedule backup"

- name: Ensure a sync job runs every sunday at 23:00
  become: true
  become_user: "{{ ansible_user }}"
  ansible.builtin.cron:
    name: "sync to drive"
    minute: "0"
    hour: "23"
    weekday: "6"
    job: "sudo sh {{ base_path }}/backup_sync/do_sync.sh > /dev/null 2>&1"
  listen: "schedule sync"

- name: Update Variables in Profile 
  ansible.builtin.template:
    src: data/profile.j2
    dest: "/root/.profile"
    mode: u=rw
  listen: 
    - "schedule backup"
    - "schedule sync"
