---
- name: Ensure a backup job runs {{ backup.schedule.description }}
  become: true
  become_user: "{{ ansible_user }}"
  ansible.builtin.cron:
    name: "take backup {{ backup.schedule.description }}"
    minute: "{{ backup.schedule.minute }}"
    hour: "{{ backup.schedule.hour }}"
    weekday: "{{ backup.schedule.weekday }}"
    job: "sudo sh {{ base_path }}/{{ backup.scripts_path }}/do_backup.sh > /dev/null 2>&1"
  listen: "schedule backup"

- name: Ensure a sync job runs {{ sync.schedule.description }}
  become: true
  become_user: "{{ ansible_user }}"
  ansible.builtin.cron:
    name: "sync to drive {{ sync.schedule.description }}"
    minute: "{{ sync.schedule.minute }}"
    hour: "{{ sync.schedule.hour }}"
    weekday: "{{ sync.schedule.weekday }}"
    job: "sudo sh {{ base_path }}/{{ backup.scripts_path }}/do_sync.sh > /dev/null 2>&1"
  listen: "schedule sync"

- name: Update Variables in Profile 
  template:
    src: data/profile.j2
    dest: "/root/.profile"
    mode: u=rw
  listen: 
    - "schedule backup"
    - "schedule sync"
