---
- name: Ensure dependencies for waveshare module are installed
  ansible.builtin.apt:
    name: 
      - git
      - python3-pip
      - python3-numpy
    state: present
  listen: "waveshare init"

- name: Check if waveshare module repository exists
  stat:
    path: "{{ base_path }}/display-lib/e-Paper"
  register: waveshare_repo
  listen: "waveshare init"

- name: Ensure waveshare module is cloned
  become: true
  become_user: "{{ ansible_user }}"
  ansible.builtin.git:
    repo: https://github.com/waveshare/e-Paper.git
    dest: "{{ base_path }}/display-lib/e-Paper"
  when: waveshare_repo.stat.exists == False
  listen: "waveshare init"

- name: Ensure waveshare module is installed
  pip:
    name: file://{{ base_path }}/display-lib/e-Paper/RaspberryPi_JetsonNano/python
  when: waveshare_repo.stat.exists == False
  listen: "waveshare init"
