---
- name: Install required packages
  apt:
    name: "{{ item }}"
  with_items:
    - ufw
    - fail2ban

- name: Start and enable UFW
  ufw:
    state: enabled

- name: Establish default incoming firewall rule
  ufw:
    policy: deny
    direction: incoming

- name: Establish default outgoing firewall rule
  ufw:
    policy: allow
    direction: outgoing

- name: Allow SSH in firewall
  ufw:
    rule: allow
    port: 22
    proto: tcp

- name: Enable SSH rate limiting
  ufw:
    rule: limit
    port: 22
    proto: tcp

- name: Allow pihole ui in firewall
  ufw:
    rule: allow
    port: 80
    proto: tcp

- name: Allow dns tcp queries in firewall
  ufw:
    rule: allow
    port: 53,67
    proto: tcp

- name: Allow dns udp queries in firewall
  ufw:
    rule: allow
    port: 53,67
    proto: udp

- name: Allow dns queries for IPv6 in firewall
  ufw:
    rule: allow
    port: 546:547
    proto: udp       
    
- name: Configure fail2ban
  copy:
    src: data/jail.local
    dest: "/etc/fail2ban/"
    owner: root
    group: root
    mode: 0644
